function [d,d1,d2,d3,d4]=distance_4_sour(sour,cands,dfr,dsd)
% without reduce !

Dlam=sour(2)-cands(:,2);

d1=abs((sour(1)-cands(:,1))/dfr);
d2=abs((min(mod(Dlam,360),mod(-Dlam,360))./(cands(:,7))));
d3=abs((sour(3)-cands(:,3))./(abs(cands(:,8))));
d4=abs((sour(4)-cands(:,4))/dsd);
d=sqrt(...
    d1.^2+...
    d2.^2+...
    d3.^2+...
    d4.^2 ...
    );
