function [d,d1,d2,d3,d4]=distance_4(const,arr,dfr,dsd)
% without reduce !

Dlam=const(2)-arr(:,2);

d1=abs((const(1)-arr(:,1))/dfr);
d2=abs((min(mod(Dlam,360),mod(-Dlam,360))./(const(7)+arr(:,7))));
d3=abs((const(3)-arr(:,3))./(abs(const(8))+abs(arr(:,8))));
d4=abs((const(4)-arr(:,4))/dsd);
d=sqrt(...
    d1.^2+...
    d2.^2+...
    d3.^2+...
    d4.^2 ...
    );
