%COLORMAP_SEL colormap selection

listcolm={'autumn' 'bone' 'colorcube' 'cool'...
   'copper' 'flag' 'gray' 'hot'...
   'hsv' 'jet' 'lines' 'pink'...
   'prism' 'spring' 'summer' 'white' 'winter'};
 
[whichcolm,sdgok]=listdlg('PromptString','Which  color map ?',...
   'Name','ColorMap selection',...
   'SelectionMode','single',...
   'ListString',listcolm);
eval(['colormap ' listcolm{whichcolm}]);