function fmnl_windexp(menutext,text1,text2)

% FMNL_WINDEXP 
%                Create a Listbox
%
%


figNumber=figure( 'Position',[200 50 600 500], ...
    'Name',menutext, ...
    'NumberTitle','off', ...
    'Color',[1 1 0.7],...
    'MenuBar','none', ...
    'Visible','on');
 
 if strcmp('Null',char(text2{3}))
    
 uicontrol( 'Position',[0.025 0.025 0.95 0.95], ...
     'Style','Listbox', ...
     'Units','normalized', ...
     'BackgroundColor',[0.50 0.50 1], ...
     'ForegroundColor',[1 1 1], ...
     'HorizontalAlignment','left', ...
     'String',text1);   
 elseif strcmp('Null',char(text1{3}))
 uicontrol( 'Position',[0.025 0.025 0.95 0.95], ...
     'Style','Listbox', ...
     'Units','normalized', ...
     'BackgroundColor',[1 1 0], ...
     'ForegroundColor',[0 0 1], ...
     'HorizontalAlignment','left', ...
     'String',text2);  
 else   
 uicontrol( 'Position',[0.025 0.50 0.95 0.50], ...
     'Style','Listbox', ...
     'Units','normalized', ...
     'BackgroundColor',[0.50 0.50 1], ...
     'ForegroundColor',[1 1 1], ...
     'HorizontalAlignment','left', ...
     'String',text1);
  
 uicontrol( 'Position',[0.025 0.015 0.95 0.475], ...
     'Style','Listbox', ...
     'Units','normalized', ...
     'BackgroundColor',[1 1 0], ...
     'ForegroundColor',[0 0 1], ...
     'HorizontalAlignment','left', ...
     'String',text2);
end
