%uidemo  some demos

% Version 1.0 - July 1998
% Part of Snag toolbox - Signal and Noise for Gravitational Antennas
% Copyright (c) 1998  Sergio Frasca - sergio.frasca@roma1.infn.it
% Department of Physics - Universita` "La Sapienza" - Rome

listdemo={'somegd' 'biggd' 'rsdo' ...
   'dsnoistat' 'dsnoistat1' 'dsnoistat2' ...
   'dsnoispows' 'dsnoispows1' 'dsnoispows2' ...
   'dsnoisound' 'dsnoisound1' ...
   'dsrunning' ...
   'dssigstat' 'dssigstat2' ...
   'dssigpows1' 'dssigsound'};
  
  [whichdemo,sdgok]=listdlg('PromptString','Which demo ? (look in the help window)',...
   'Name','Demo list',...
   'SelectionMode','single',...
   'ListString',listdemo);

%str=strcat(answcg,'=',listprgd(whichfun),'(',gdsscra(selgd1),...
%   ',',gdsscra(selgd2),');');
eval(listdemo{whichdemo});
