%uiproc2gd  process two gds

% Version 1.0 - July 1998
% Part of Snag toolbox - Signal and Noise for Gravitational Antennas
% Copyright (c) 1998  Sergio Frasca - sergio.frasca@roma1.infn.it
% Department of Physics - Universita` "La Sapienza" - Rome

promptcg='Name of the new gd';
defacg={'g'};
answcg=inputdlg(promptcg,'New gd',1,defacg);

listgd;

nmenu=gdol.n;

gdsscra=gdol.name;
  
[selgd1,sgdok]=listdlg('PromptString','Which gd for first input ?',...
   'SelectionMode','single',...
   'ListString',gdsscra);
  
[selgd2,sgdok]=listdlg('PromptString','Which gd for second input ?',...
   'SelectionMode','single',...
   'ListString',gdsscra);

listprgd={'Addition' 'Subtraction' 'Products' 'Division'...
   ' ' 'Minimum' 'Maximum'...
   ' ' 'Cross-correlation'...
   ' ' 'gd(2) with gd(1) abscissa' 'gd(2) with gd(1) ordinate as abscissa'};

listprgd1={'plus' 'minus' 'times' 'rdivide'...
   ' ' 'minimum_gd' 'maximum_gd'...
   ' ' 'gd_crcorfft'...
   ' ' 'gd_getabsc' 'gd_gdabsc'};
  
[whichfun,sdgok]=listdlg('PromptString','Which function to set ?',...
   'Name','Two gds processing',...
   'SelectionMode','single',...
   'ListString',listprgd);

str=strcat(answcg,'=',listprgd1(whichfun),'(',gdsscra(selgd1),...
   ',',gdsscra(selgd2),');');
eval(str{1});
