%uiproc1gd  process one gd

% Version 1.0 - July 1998
% Part of Snag toolbox - Signal and Noise for Gravitational Antennas
% by Sergio Frasca - sergio.frasca@roma1.infn.it
% Department of Physics - Universita` "La Sapienza" - Rome

promptcg='Name of the new gd';
defacg={'g'};
answcg=inputdlg(promptcg,'New gd',1,defacg);

listgd;

nmenu=gdol.n;

gdsscra=gdol.name;

[seldelgd1,sdgok]=listdlg('PromptString','Which gd input ?',...
   'SelectionMode','single',...
   'ListString',gdsscra);

listprgd={...
   'Power Spectrum' 'Fourier Transform' 'Time-Frequency power spectrum' 'Time-Frequency innovation power spectrum'...
   'Autocorrelation' 'Time domain filtering' 'Frequency domain filtering'...
   'Psd' 'Hilbert Transform' 'Worm Analysis'...
   ' ' 'Real' 'Imag' 'Abs' 'Phase' '"atan3" (integer phase - in circle angles)'...
   ' ' 'Polinomial' 'Power (def sqrt)' 'Logarithm' 'Exponential' 'Sinusoid'...
   ' ' 'Integral' 'Derivative'...
   ' ' 'Selection on amp, ind, absc'...
   ' ' 'Abscissa out' 'Linear transformation of the abscissa'...
			'Polinomial transformation of the abscissa'};
listprgd1={
   'igd_pows' 'dft_gd' 's_tfpows' 's_dtfpows' 'gd_acorfft' 'tfilt_gd'...
   'ffilt_gd' 'psd_gd' 'gd_hilb' 'gd_worm'...
   ' ' 'real_gd' 'imag_gd' 'abs_gd' 'phase_gd' 'atan3'...
   ' ' 'poli_gd' 'power_gd' 'log_gd' 'exp_gd' 'sin_gd'...
   ' ' 'inte_gd' 'deri_gd'...
   ' ' 'sel_gd'...
   ' ' 'abscout_gd' 'ltabsc' 'poliabsc_gd'};
  
  [seldelgd2,sdgok]=listdlg('PromptString','Which function to set ?',...
   'Name','One gd processing',...
   'ListSize',[300 300],...
   'SelectionMode','single',...
   'ListString',listprgd);

str=strcat(answcg,'=',listprgd1(seldelgd2),'(',gdsscra(seldelgd1),');');
eval(str{1});
