%uisetgdnoise  sets gds

% Version 1.0 - July 1998
% Part of Snag toolbox - Signal and Noise for Gravitational Antennas
% Copyright (C) 1998  Sergio Frasca - sergio.frasca@roma1.infn.it
% Department of Physics - Universita` "La Sapienza" - Rome

listftsgd={'White noises' 'First order process' 'Second order process'...
      'Random Walk' 'Markov process' 'Complex Markov process'...
      'Poisson processes'};
listftsgd1={'igd_noise' 'o1proc_gd' 'o2proc_gd' 'rwalk_gd' 'mrw'...
      'cmrw' 'gd_poisson'};
  
  [seldelgd1,sdgok]=listdlg('PromptString','Which stochastic signal ?',...
   'Name','Stochastic processes',...
   'ListSize',[250 150],...
   'SelectionMode','single',...
   'ListString',listftsgd);

eval([answnamwgd{1} '=' listftsgd1{seldelgd1}])
